[ip]
address = [
    "https://ifconfig.me",
    "http://ip.sb",
    "http://ip.gs",
    "https://icanhazip.com",
    "https://ipecho.net/plain",
    "https://ifconfig.minidump.info/ip",
    "https://ip.3322.org",
    "https://icanhazip.com",
]
