name: Build
on: [push, pull_request]
permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26.5'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v6

      - name: Get dependencies
        run: go mod download

      - name: Test
        run: go test -race -coverprofile=coverage.out ./...

      - name: Check the build
        shell: bash -l {0}
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          make build
